language: php
php:
- 5.3
- 5.4
- 5.5
env:
    global:
        secure: "dSCWfYD3TC9NB10MSdu92owrG1QBIek0KYvUeRCNHGfh+OpeDGS8meTjUTXDRUPQZshsmZQkDfWGZ+7itgQZQfKkHu9RC9Vbn/S/TKbOQMuuUORxt/wPhGQgHUFIwwdWpdcyaUwVIZm92t+yHXiKSP4A8T/coChm4cnT1XeIwYo="
install:
    - composer self-update
    - composer update --prefer-dist
script:
- sed -i s/__HOOK_ID__/${HOOK_ID}/ ./tests/Idobata/IdobataTest.php
- composer install
- ./vendor/bin/phpunit --testdox ./tests
notifications:
  hipchat:
    rooms:
      secure: fAnbDlW6fIw3J+n+t8Azsvd9i7X1r9/IhDY/0+tlABUVA3SUPVTpW0u+v3GvlQyJQcMabDztxZMqMxRj7O4ETEhLhDHxWPLTCg81r0exzGHOMjy+p1jyPnbiDhBJVX1E5hij3jSz093eTbgdrSsrCYCAPt4QVTbvrcjjxHLPUTU=
