language: php
php:
- 5.3
- 5.4
- 5.5
- hhvm
env:
    global:
        secure: "g9Ai1zSujLcLQWJ5PI/XQTthhatFzQdUV3XnCX961+LRzftQ5lKXb/a/RPtmTXoMuECViJoohE9Xxv8gvUwVnRSugo7fIDDuzWuuaCPdyVnqm6gS0boLm+JDmD7Qqo5/mbPUO3WwyjuY3u6qrV5yax5tXPLzkWVzP+CqMyLPzMc="
script:
- sed -e s/__HOOK_ID__/${HOOK_ID}/ ./tests/Idobata/IdobataTest.php
- composer install
- ./vendor/bin/phpunit --testdox ./tests
notifications:
  hipchat:
    rooms:
      secure: fAnbDlW6fIw3J+n+t8Azsvd9i7X1r9/IhDY/0+tlABUVA3SUPVTpW0u+v3GvlQyJQcMabDztxZMqMxRj7O4ETEhLhDHxWPLTCg81r0exzGHOMjy+p1jyPnbiDhBJVX1E5hij3jSz093eTbgdrSsrCYCAPt4QVTbvrcjjxHLPUTU=
